version: 2

jobs:
  deploy:
    branches:
      only:
        - main
    context: 
      - deploy
    docker:
      - image: node:12.18.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: deploy
          command: yarn deploy
