version: 2

jobs:
  deploy:
    docker:
      - image: node:12.18.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: deploy
          command: yarn deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy:
        context: deploy
        branches:
          only:
            - main
       